baseurl: "https://antihashed.xyz/"
title: "Antihashed Podcast"
theme: "zen"
languageCode: "en-GB"       # Set your language code (only needed for none multilingual sites).

params:
  cookieConsent: false       # Show cookie consent form, default false.
  contact: "email@antihashed.xyz"
  description: "Two grumpy men talk about bitcoin and starcraft"           # Set site description, used in meta tags and JSON-LD
  feedlinks: false           # Show feed links in the footer.
  footer: "RSS Feed address: https://antihashed.xyz/podcast/index.xml"
  logoWidth: 200            # Set logo width, defaults to none.
  menuInHeader: true        # Move the main menu to the header, default false.
  mobileMenu: true          # Turn on a mobile menu on small screens, default false.
  poweredby: true           # Show powered by hugo in footer
  relatedposts: true        # Show related posts under a "See also" section, default false.
  sidebar: true             # Show a sidebar to the right, default false.
  submitted: true           # Show author and date information for a post.

  podcast:
    title: "Antihashed"                 # * Feed title, defaults to site title (iTunes).
    description: "Two grumpy men talk about bitcoin and starcraft"           # * Feed description/summary, defaults to  site description (iTunes).
    image:  logo.png                # * Feed image, place inside assets directory (iTunes).
    category:
      name: "Technology"                # * Feed category (iTunes).
    explicit: true    # Feed explicit setting, default to false (iTunes).
    author: "Constant and Fiatjaf"                # Feed author (iTunes).
    owner:
      name: "Constant and Fiatjaf"               # Feed owner name (iTunes).
      email: "email@antihashed.xyz"               # Feed owner e-mail (iTunes).
    type: episodic   # Podcast type, defaults to episodic (iTunes).
    cdn:  "https://antihashed.us-east-1.linodeobjects.com"                  # CDN url, no slash on end (https://cdn.example.org).
    local: false            # Are the audio files local (true) or remote (false), default to true.
